---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  annotations:
    createdAt: Thursday, 13-Aug-26 07:11:51 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: 4.20.0-202607290013.p2.g9b18640.assembly.stream.el9-9b18640
  name: itms-operator-0
spec:
  imageTagMirrors:
  - mirrors:
    - ip-10-0-61-241.us-east-2.compute.internal:8443/rhoai/nvidia/cloud-native
    source: nvcr.io/nvidia/cloud-native
  - mirrors:
    - ip-10-0-61-241.us-east-2.compute.internal:8443/rhoai/nvidia
    source: nvcr.io/nvidia
  - mirrors:
    - ip-10-0-61-241.us-east-2.compute.internal:8443/rhoai/nvidia/k8s
    source: nvcr.io/nvidia/k8s
