apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhoai-copilot
  labels:
    app: rhoai-copilot
    app.kubernetes.io/part-of: rhoai-copilot
spec:
  to:
    kind: Service
    name: rhoai-copilot
  port:
    targetPort: dashboard
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
